# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170805_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomstudent',
            old_name='roomId',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roomstudent',
            old_name='studentId',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='stublacklist',
            old_name='roomId',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='stublacklist',
            old_name='studentId',
            new_name='student',
        ),
    ]
