# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170806_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isTeacher',
            new_name='is_teacher',
        ),
    ]
