# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170809_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='createTime',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='roomName',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='studentNum',
            new_name='student_num',
        ),
        migrations.AddField(
            model_name='roomstudent',
            name='can_speak',
            field=models.BooleanField(default=True),
        ),
    ]
