# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170809_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stublacklist',
            name='room',
        ),
        migrations.RemoveField(
            model_name='stublacklist',
            name='student',
        ),
        migrations.AddField(
            model_name='roomstudent',
            name='can_watch',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='stuBlackList',
        ),
    ]
