# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170814_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='my_file',
            field=models.FileField(default='', upload_to='./upload/'),
            preserve_default=False,
        ),
    ]
