# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_room_my_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='my_file',
        ),
    ]
